apiVersion: apps/v1
kind: Deployment
metadata:
  name: forest-fire-app-deploy
  labels:
    type: webapp
spec:
  selector:
    matchLabels:
      app: forest-fire-app
  replicas: 3
  template:
    metadata:
      labels:
        app: forest-fire-app
    spec:
      containers:
        - name: forest-fire-app
          image: forest-fire-app:latest
          livenessProbe:
                    httpGet:
                      path: /healthz
                      port: 8000
                    initialDelaySeconds: 15
                    periodSeconds: 10
                    failureThreshold: 3
          readinessProbe:
                    httpGet:
                      path: /ready
                      port: 8000
                    initialDelaySeconds: 5
                    periodSeconds: 10
                    failureThreshold: 1
          ports:
            - containerPort: 8000
      strategy:
        type: RollingUpdate
        rollingUpdate:
          maxUnavailable: 1
          maxSurge: 1