name: CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to Minikube
      run: |
        kubectl create --filename deployment.yaml
        kubectl create --filename service.yaml
        # kubectl create deployment forest-fire-app --image=forest-fire-app:latest
        # kubectl expose deployment forest-fire-app --type=LoadBalancer --port=8000