name: CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t forest-fire-app:latest .

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Kubernetes
      run: |
        # Ensure Minikube or Kubernetes is installed
        minikube start || true
        kubectl cluster-info

    - name: Deploy to Kubernetes
      run: |
        kubectl create deployment forest-fire-app --image=forest-fire-app:latest
        kubectl expose deployment forest-fire-app --type=LoadBalancer --port=8000